apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-template-service
  namespace: python-template-service
  labels:
    app: python-template-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-template-service
  template:
    metadata:
      labels:
        app: python-template-service
    spec:
      containers:
        - name: python-template-service
          image: python-template-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: python-template-service-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: python-template-service-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: python-template-service-secret
                  key: AWS_REGION
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: python-template-service-configmap
                  key: DEBUG
            - name: API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: python-template-service-configmap
                  key: API_VERSION
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:  
                  name: python-template-service-configmap
                  key: ENVIRONMENT
---
apiVersion: v1
kind: Service
metadata:
  name: python-template-service-service
  namespace: python-template-service
spec:
  selector:
    app: python-template-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8000
      nodePort: 30000
